Removed forms.js
icssc-projects/peterportal-public-api pull request #185
Opened 2022-03-18 21:02 UTC by nathantoannguyen

## Reference Issues
#146 

## Summary of Change/Fix 
Deleted files in /docs/js and the same file names under extra_javascript in mkdocs.yml

## Test Plan
Ensured files were not present in respective locations

2022-03-19 18:30 UTC, ramanxg requested changes
We actually still need custom.js and termynal.js. We just don't need the forms.js. Can you add them back?

2022-03-22 01:24 UTC, nathantoannguyen commented
I added the custom.js and termynal.js files back as well as included them in the mkdir file.

2022-03-22 04:25 UTC, ramanxg approved these changes

2022-03-22 04:26 UTC, ramanxg commented
Great, thanks!

2022-03-22 04:26 UTC, merged