Removed Moesif from app.js
icssc-projects/peterportal-public-api pull request #187
Opened 2022-03-19 02:41 UTC by JakeGerber

## Reference Issues
Removed Moesif from app.js

## Summary of Change/Fix 
- Verified that changes did not mess up api calls.

## Test Plan
Closes #117

2022-03-19 18:34 UTC, ramanxg requested changes
Thanks! Just one small change I've requested.

2022-03-19 18:34 UTC, ramanxg commented on app.js
> -  module.exports.handler = moesif_wrapper;
We actually still need this line, but instead we need to let it be `sentry_wrapper` instead.

2022-03-20 00:57 UTC, JakeGerber commented
Fixed the app file line. How would I uncommit the package-lock.json file from the pull request?

2022-03-20 01:24 UTC, ramanxg commented
> Fixed the app file line. How would I uncommit the package-lock.json file from the pull request @ramanxg?

You can use checkout the file from master `git checkout origin/master package-lock.json`.

2022-03-20 01:50 UTC, JakeGerber commented
> > Fixed the app file line. How would I uncommit the package-lock.json file from the pull request @ramanxg?
> 
> You can checkout the file from master `git checkout origin/master package-lock.json`.

Doesn't do anything. Just says it has updated 0 paths.

2022-03-20 08:22 UTC, ramanxg approved these changes

2022-03-20 08:22 UTC, merged