Helper overhaul
icssc-projects/peterportal-public-api pull request #51
Opened 2021-02-08 00:29 UTC by ChaseC99

To share helpers between rest and graphql, this PR moves the helper functions into their own separate folder.
It also fixes errors in the unit and integration tests.
 
Todo:
- Have GraphQL reference the helpers instead of the cache directly
- Improve the grades helper to make it more accessible to graphql
- Add tests for graphql
- Add tests for API keys and graphql-playground

## Test Plan
- `npm test` and verify that all tests pass

2021-02-09 20:36 UTC, ramanxg requested changes
This is awesome, thanks for this. One thing is, when doing the grades in GraphQL, if I give a bad parameter (i.e. an instructor that doesn't exist), I get an error (which is correct), but the error looks a little weird.

All that's necessary is to set the message to the message from the error json. 

Instead of this: (current)
```
"errors": [
    {
      "message": "Unexpected error value: { timestamp: \"Tue, 09 Feb 2021 20:32:12 GMT\",  
 status: 400, error: \"Bad Request: Invalid syntax in parameters\", message: \"Invalid syntax.     found in parameters. Exception occured at 'PATTIS, R' in the [instructor] query value\" }",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "grades"
      ]
    }
  ],
  "data": {
    "grades": null
  }
}
```

Something like this: 
```
"errors": [
    {
      "message": Invalid syntax found in parameters. Exception occured at 'PATTIS, R' in the [instructor] query value\" }",
      ...
```

2021-02-10 06:31 UTC, ChaseC99 commented
GraphQL was a little annoying with the error handling. I had to actually throw an error instead of a JSON literal like I was doing before. So I created a simple `ValidationError` that extends `Error`. Could've probably just used an existing error type like `SyntaxError` but I figured `ValidationError` was cleaner.

Lemme know if the way I'm handling these errors looks ok to you!

2021-02-10 06:34 UTC, ramanxg approved these changes

2021-02-10 06:34 UTC, ramanxg commented
Awesome, it looks great. I'll merge it.

2021-02-10 06:34 UTC, merged