First Commit
icssc-projects/peterportal-public-api pull request #74
Opened 2021-05-05 06:57 UTC by Edwu29

1. Updated elastic search DB (running npm refresh script)
2. Removed phone from GraphQL schema InstructorType

```javascript
const instructorType = new GraphQLObjectType({
  name: 'Instructor',
  fields: () => ({
    name: { type: GraphQLString },
    ucinetid: { type: GraphQLString },
    title: { type: GraphQLString },
    department: { type: GraphQLString },
    schools: { type: GraphQLList(GraphQLString) },
    related_departments: { type: GraphQLList(GraphQLString) },
    course_history: { 
      type: GraphQLList(courseType),
      resolve: (instructor) => {
        return getInstructor(instructor.ucinetid)["course_history"].map(course_id => getCourse(course_id.replace(/ /g, "")));
      }
    }
  })
});
```
3. Updated docs: removed phone
![image](https://user-images.githubusercontent.com/39328613/117105803-9e8e5f00-ad33-11eb-9896-dfcf804668be.png)

4. Made changes to unit tests to match cache data 
![image](https://user-images.githubusercontent.com/39328613/117105880-c54c9580-ad33-11eb-8b71-d6d6ef0e67a7.png)

    Updated prerequisite_text and prerequisite_for to be "arrayContaining"
    ![image](https://user-images.githubusercontent.com/39328613/117106233-5cb1e880-ad34-11eb-84aa-c5c9427198ce.png)

2021-05-05 22:42 UTC, ChaseC99 requested changes
GraphQL changes look solid to me! As long as all the tests pass, I think it should be good to go👍🏼

Only other thing is to revert the stuff I left comments on. Looks like a few extra things slipped into the commit.

2021-05-05 22:42 UTC, ChaseC99 commented on .env.example
> -SENTRY_DSN=
We probably shouldn't delete this because it's helpful for people first getting set up. (unless it's no longer necessary?)

2021-05-05 22:42 UTC, ChaseC99 commented on app.js
> +// });
I know you needed to comment this out to get it to run, but I don't think it's should be commented out for production. Will defer to @ramanxg.

2021-05-05 22:42 UTC, ChaseC99 commented on app.js
> +//app.use(moesifMiddleware);
Same as above

2021-05-05 22:56 UTC, ChaseC99 commented
Also this PR is very well done!! Good description, screenshots, and linked the relevant issue 👌 

Only other suggestions would be to give the title a better name (E.g. "Remove Phone Numbers"  instead of "First Commit") and maybe add a Test Plan to the description, explaining how you verified the your changes worked. 

For Example:
> ### Test Plan
> - Verify Phone Numbers don't show up in GraphQL Playground
> - Verify Phone Numbers don't show up in REST response 
> - run `npm run test`

Overall though great work 💯

2021-05-06 01:32 UTC, ramanxg commented on .env.example
> -SENTRY_DSN=
Yes, this should be kept!

2021-05-06 01:34 UTC, ramanxg commented on app.js
> +// });
To prevent this from being commented out, you should create a .env file in your folder and use the keys in the notion. This should solve the issue of you having to comment this out again.

2021-05-06 01:40 UTC, ramanxg requested changes
This looks good! I like the detail in the pr as well. Just a few changes, and some that Chase suggested as well. Awesome stuff!!

2021-05-06 01:40 UTC, ramanxg commented on tests/unit/instructor.helper.unit.test.js
> +                "course_history": expect.arrayContaining(["COMPSCI 290", "COMPSCI 299", "I&C SCI 90", "I&C SCI 193", "I&C SCI 33", "COMPSCI 199", "I&C SCI 7", "COMPSCI H198", "I&C SCI 46", "COMPSCI 2
Rather than adding new elements to this array, let's instead remove some.  arrayContaining will check that the array is a superset of the one given to the function, so maybe change this so that it includes classes that he most definitely teaches. For example `I&C SCI 33`, and `I&C SCI 46` and others. 

The way the course_history is parsed is that it only goes a few years back (otherwise it would be infinite). So let's include courses he most definitely teaches. 

The ones I would guess are good

- ICS 33
- ICS 46
- ICS 90
- ICS 193

2021-05-06 22:18 UTC, Edwu29 commented on .env.example
> -SENTRY_DSN=
Added back!

2021-05-06 22:19 UTC, Edwu29 commented on app.js
> +// });
Uncommented it

2021-05-06 22:19 UTC, Edwu29 commented on app.js
> +//app.use(moesifMiddleware);
Uncommented as well

2021-05-06 22:21 UTC, Edwu29 commented on tests/unit/instructor.helper.unit.test.js
> +                "course_history": expect.arrayContaining(["COMPSCI 290", "COMPSCI 299", "I&C SCI 90", "I&C SCI 193", "I&C SCI 33", "COMPSCI 199", "I&C SCI 7", "COMPSCI H198", "I&C SCI 46", "COMPSCI 2
Updated to contain the courses above.
![image](https://user-images.githubusercontent.com/39328613/117372637-ae668a00-ae7e-11eb-8ceb-7ce07a2c33de.png)

2021-05-07 06:15 UTC, ramanxg approved these changes

2021-05-07 06:16 UTC, ramanxg commented
Great stuff! First PR woot woot.

2021-05-07 08:49 UTC, ChaseC99 approved these changes
Yay congrats on the first PR 🎉

2021-05-07 09:00 UTC, merged